Cambios varios y rebase
axadoo/mercadopago pull request #35
Opened 2022-09-09 14:25 UTC by filoquin

[WIP0] backport 15 module changes.

[FIX] Reordeno para poder comparar con el anterior

[FIX] CLEAN controller code

[FIX] Modifico el TMP para que CVV sea tipo pass
[FIX] Agrego customer_id en el token para no buscarlo todo el tiempo [FIX] Agrego mas datos de customer para mejorar la validacion sin CVV

Create push_to_another_repo.yml

[DEL] remove unused gh action

2022-09-09 14:25 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/axadoo/mercadopago/pull/35).

2022-09-14 14:34 UTC, Bruno-Zanotti requested changes
@filoquin paso algunos comentarios para mezclar

2022-09-14 14:34 UTC, Bruno-Zanotti commented on payment_mercadopago/controllers/main.py
> +        _logger.warning(kwargs)
borrar

2022-09-14 14:34 UTC, Bruno-Zanotti commented on payment_mercadopago/controllers/main.py
> +        _logger.warning(token)
borrar

2022-09-14 14:34 UTC, Bruno-Zanotti commented on payment_mercadopago/controllers/main.py
>          """ Process the data sent by MercadoPago to the webhook based on the event code.
Podríamos borrar porque ya no se usa? chequear por las dudas

2022-09-14 15:58 UTC, maq-adhoc commented on payment_mercadopago/controllers/main.py
>          """ Process the data sent by MercadoPago to the webhook based on the event code.
No deberíamos borrarlo porque MP requiere un URL de notificación, la llama después del pago y espera un status 200 OK. 
Esta URL tendría una funcionalidad mayor en los casos en el cliente rechace un pago o pida devolución (esto no esta aun contemplado) pero MP informa mediante esa URL.  
También en los casos en que el pago quede un estado intermedio (autorizado por ejemplo, pero no confirmado)

2022-09-14 16:02 UTC, maq-adhoc commented on payment_mercadopago/controllers/main.py
> +        _logger.warning(kwargs)
Listo

2022-09-14 16:02 UTC, maq-adhoc commented on payment_mercadopago/controllers/main.py
> +        _logger.warning(token)
listo

2022-09-15 11:34 UTC, Bruno-Zanotti commented on payment_mercadopago/controllers/main.py
>          """ Process the data sent by MercadoPago to the webhook based on the event code.
Ah perdón seleccioné el otro, por lo que veo nos quedó duplicado el método que recibe la notificación:
```
- mercadopago_notification: url /payment/mercadopago/notify
- mercadopago_s2s_notification: url /payment/mercadopago/notification
```

Si no me equivoco "mercadopago_notification" no se usaría nunca no?

2022-09-15 19:55 UTC, maq-adhoc commented on payment_mercadopago/controllers/main.py
>          """ Process the data sent by MercadoPago to the webhook based on the event code.
¡Es Verdad @Bruno-Zanotti!  ya los saque.

2022-09-16 12:46 UTC, Bruno-Zanotti approved these changes

2022-09-16 12:47 UTC, merged