[FIX] Evaluate if request is available when define the CVV_token. If …
axadoo/mercadopago pull request #39
Opened 2022-09-21 12:45 UTC by maq-adhoc

…not available assume that the token is valid.

2022-09-21 12:46 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/axadoo/mercadopago/pull/39).

2022-09-23 13:31 UTC, Bruno-Zanotti requested changes

2022-09-23 13:31 UTC, bruno-zanotti commented on payment_mercadopago/__manifest__.py
> +    'version': '13.0.1.6.1',
@filoquin acá me olvidé de comentarte el otro día, en realidad solemos aumentar el pen último número, sería: 13.0.1.7.0 en este caso

2022-09-23 13:43 UTC, filoquin commented on payment_mercadopago/__manifest__.py
> +    'version': '13.0.1.6.1',
Listo

2022-09-23 13:54 UTC, Bruno-Zanotti commented
@roboadhoc r+

2022-09-23 14:11 UTC, merged