[IMP] Add binary mode in payment acquirer
axadoo/mercadopago pull request #54
Opened 2023-01-25 12:09 UTC by maq-adhoc

2023-01-25 12:10 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/plugberry/mercadopago/pull/54).

2023-02-08 15:48 UTC, Bruno-Zanotti commented on payment_mercadopago/models/mercadopago_request.py
> +        #return {'status':'pending', 'status_detail':'tests', 'id':int(random.random()*5000)}
@filoquin esto lo podemos borrar entiendo no?

2023-06-15 16:53 UTC, augusto-weiss commented
@roboadhoc r+

2023-06-16 09:55 UTC, Bruno-Zanotti commented
@roboadhoc rebase-ff

2023-06-16 09:56 UTC, roboadhoc commented
Merge method set to rebase and fast-forward.

2023-06-16 09:57 UTC, Bruno-Zanotti commented
@roboadhoc override=ci/oba_without_tests

2023-06-16 09:57 UTC, roboadhoc commented
I'm sorry, @Bruno-Zanotti: you are not allowed to override this status.

2023-09-04 11:05 UTC, Bruno-Zanotti requested changes

2023-09-04 11:05 UTC, Bruno-Zanotti commented on payment_mercadopago/models/mercadopago_request.py
> -
eliminar cambio

2023-09-04 11:05 UTC, Bruno-Zanotti commented on payment_mercadopago/models/payment.py
> +    mercadopago_binary = fields.Boolean('Use binary mode', default=True)
cambiar versión manifest

2023-09-06 15:25 UTC, Bruno-Zanotti commented
@roboadhoc r+

2023-09-06 15:30 UTC, closed without merging