[IMP] add wizards check payment in MP
axadoo/mercadopago pull request #55
Opened 2023-03-13 22:40 UTC by maq-adhoc

2023-03-13 22:41 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/plugberry/mercadopago/pull/55).

2023-07-17 14:19 UTC, maq-adhoc commented
@roboadhoc r+

2023-07-17 15:16 UTC, roboadhoc commented
@maq-adhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2023-07-17 16:28 UTC, maq-adhoc commented
@roboadhoc  rebase-merge

2023-07-17 16:29 UTC, roboadhoc commented
Merge method set to rebase and merge, using the PR as merge commit message.

2023-07-17 16:30 UTC, roboadhoc commented
@maq-adhoc unable to stage: merge conflict

2023-07-18 11:44 UTC, Bruno-Zanotti requested changes

2023-07-18 11:44 UTC, Bruno-Zanotti commented on payment_mercadopago/wizards/__init__.py
> +from . import check_payment
```suggestion
from . import check_payments
```

2023-07-19 15:01 UTC, Bruno-Zanotti commented
@roboadhoc r+

2023-07-19 15:05 UTC, closed without merging